# server.port : 9090 으로 고정
server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: front-end
          uri: http://localhost:8080
          predicates:
            - Path=/board/**
        - id: back-end
          uri: http://localhost:8081
          predicates:
            - Path=/back/**
